#Program to run
program: 'train.py'
#Sweep search method: random, grid or bayes
method: 'random'

# Project this sweep is part of
project: 'sweep_01'
entity: 'nyrenw'

# Metric to optimize
metric:
  name: 'Validation MSE'
  goal: 'minimize'

# Parameters search space
parameters:
  lr: 
    values: [0.001, 0.0005, 0.0001, 0.00005, 0.00001]
  hidden_channels:
    values: [100, 150, 200, 250, 300, 500, 750, 1000]
  num_layers:
    values: [4, 8, 12, 16]
  num_timesteps:
    values: [1, 2, 4, 8]
  dropout:
    values: [0.0, 0.05, 0.1]
  num_workers:
    value: 0
  ep_train:
    value: 10